[book]
title = "Anvilforge"
authors = ["Anvilforge contributors"]
description = "Laravel-equivalent Rust web framework"
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/anvilforge/anvilforge"
edit-url-template = "https://github.com/anvilforge/anvilforge/edit/main/docs/{path}"
site-url = "/anvilforge/"

[output.html.fold]
enable = true
level = 1

[output.html.print]
enable = true
page-break = true
